package com.knowledgespike.core.type.shared

object MatchTypes {
    val validMatchTypes: List<String>
        get() = listOf(
            "a",
            "bbl",
            "bpl",
            "cc",
            "cpl",
            "ct",
            "engtt",
            "f",
            "fran",
            "hund",
            "icct",
            "ipl",
            "itt",
            "kia",
            "log",
            "lpl",
            "minc",
            "mint",
            "mintt",
            "ncl",
            "nztt",
            "o",
            "prem",
            "ps",
            "psl",
            "qea",
            "rt",
            "sacboc",
            "satt",
            "sec",
            "set",
            "sett",
            "ss",
            "t",
            "tt",
            "ua",
            "uf",
            "uitt",
            "uo",
            "ut",
            "uwc",
            "wa",
            "wbbl",
            "wc",
            "wch",
            "wcsl",
            "wctt",
            "wf",
            "whund",
            "wid",
            "wipl",
            "witt",
            "wmisc",
            "wnztt",
            "wo",
            "wt",
            "wtc",
            "wtt",
            "wwc",
            "wwctt",
            "wuo",
            "wuitt"
        )

    val internationalMatchTypes = listOf("t", "wt", "o", "wo", "itt", "witt")
    val multiInningsMatchTypes = listOf("t", "f", "wt", "wf", "sec", "minc", "ut")
}
