export interface MatchDetails {
  homeTeam: string,
  awayTeam: string,
  resultString: string,
  durationType: string,
  tournament: string,
  matchType: string,
  homeTotal1: number,
  homeWickets1: number,
  homeOvers1: string | undefined,
  homeDeclared1: boolean,
  awayTotal1: number,
  awayWickets1: number,
  awayOvers1: string | undefined,
  awayDeclared1: boolean,
  homeTotal2: number,
  homeWickets2: number,
  homeOvers2: string | undefined,
  homeDeclared2: boolean,
  awayTotal2: number,
  awayWickets2: number,
  awayOvers2: string | undefined,
  awayDeclared2: boolean,
}
